name: Push to Hugging Face Space

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
          lfs: true

    - name: Install Git LFS (Large File Support)
      run: git lfs install

    - name: Install Python Dependencies
      run: |
        pip install setuptools distlib
        pip install -r requirements.txt
          
    - name: Push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN_LOCALVERSION }}
      run: |
        git remote add hf https://user:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/mlops-cs553-fall24/Local-Chatbot
        git push hf main --force
